// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2ZaiWa055yMGTuudaEO1Twt_E9w6WJc',
    appId: '1:1020735028944:web:d4dace54b13265b66e68d5',
    messagingSenderId: '1020735028944',
    projectId: 'musicapp-89a7b',
    authDomain: 'musicapp-89a7b.firebaseapp.com',
    storageBucket: 'musicapp-89a7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwxzionaRanK_WaFD5EomNd4XLcBDEkc',
    appId: '1:1020735028944:android:abc251b883cd09c56e68d5',
    messagingSenderId: '1020735028944',
    projectId: 'musicapp-89a7b',
    storageBucket: 'musicapp-89a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWFVNlByQaSQy9tXozBUqdAwGbup15SRQ',
    appId: '1:1020735028944:ios:737bd7c9149c99276e68d5',
    messagingSenderId: '1020735028944',
    projectId: 'musicapp-89a7b',
    storageBucket: 'musicapp-89a7b.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWFVNlByQaSQy9tXozBUqdAwGbup15SRQ',
    appId: '1:1020735028944:ios:737bd7c9149c99276e68d5',
    messagingSenderId: '1020735028944',
    projectId: 'musicapp-89a7b',
    storageBucket: 'musicapp-89a7b.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj2ZaiWa055yMGTuudaEO1Twt_E9w6WJc',
    appId: '1:1020735028944:web:4bec773349dcc4036e68d5',
    messagingSenderId: '1020735028944',
    projectId: 'musicapp-89a7b',
    authDomain: 'musicapp-89a7b.firebaseapp.com',
    storageBucket: 'musicapp-89a7b.firebasestorage.app',
  );
}
